apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: observai-backend-query  
resources:
  # - volume.yaml
  - volumeclaim.yaml
  - eventListener.yaml
  - trigger.yaml
  - triggerbinding.yaml
  - triggerTemplate.yaml
  - pipeline.yaml
  - route.yaml