apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-template-query
  namespace: testing-workspace
spec:
  params:
  - name: url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: observai-query-backend-
      spec:
        pipelineRef:
          name: observai-query-backend
        workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: maven-source-pvc-query
        - name: docker-credentials
          secret:
            items:
              - key: .dockerconfigjson
                path: config.json
            secretName: sharanya-zaga-pull-secret
        - name: maven-settings
          emptyDir: {}
        - name: maven-local-m2
          persistentVolumeClaim:
            claimName: query-maven-local-m2-pvc    
        params:
        - name: url
          value: $(tt.params.url)
        - name: revision
          value: pipeline
        - name: DOCKERFILE
          value: src/main/docker/Dockerfile.jvm
        - name: OC_NAMESPACE
          value: testing-workspace
        - name: DEPLOYMENT_NAME
          value: test-observai-query-api
        - name: DIRECTORY
          value: tekton/query-backend/oc_manifests/
        - name: IMAGE_NAME
          value: quay.io/zagaos/test-observai-query-api





