apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: github-trigger-query
  namespace: observai-pipeline
spec:
  interceptors:
    - ref:
        name: cel-interceptor
      params:
        - name: filter
          value: "body.ref == 'refs/heads/pipeline' && header.match('X-GitHub-Event', 'push')"
  bindings:
    - ref: github-binding-query
  template:
    ref: github-template-query