apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-template-query
  namespace: testing-workspace
spec:
  params:
  - name: url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: observai-backend-query-
      spec:
        pipelineRef:
          name: observai-backend-query
        workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: shared-volume-claim-1
        params:
        - name: url
          value: $(tt.params.url)
        - name: revision
          value: develop
        - name: DOCKERFILE
          value: src/main/docker/Dockerfile.jvm
        - name: IMAGE_NAME
          value: quay.io/zagaos/observai-query-api





