kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: observai-ui
  namespace: observai-pipeline
  labels:
    app: observai-ui
    app.kubernetes.io/part-of: observai
    app.openshift.io/runtime: js
    app.openshift.io/runtime-namespace: observai-pipeline
spec:
  strategy:
    type: Recreate
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - observai-ui
        from:
          kind: ImageStreamTag
          namespace: observai-pipeline
          name: 'observai-ui:latest'
  replicas: 1
  selector:
    app: observai-ui
  template:
    metadata:
      labels:
        app: observai-ui
    spec:
      containers:
        - name: observai-ui
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          image: >-
            image-registry.openshift-image-registry.svc:5000/observai-pipeline/observai-ui:latest


