apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: testing-workspace
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: testing-workspace
spec:
  selector:
    matchLabels:      
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
        - name: zookeeper
          image: docker.io/confluentinc/cp-zookeeper
          ports:
            - name: http-2181
              containerPort: {{.Values.kafka.zookeeper.targetPort}}
              protocol: TCP
          env:
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"               
        - name: observai-kafka
          image: docker.io/confluentinc/cp-kafka
          ports:
            - name: http-9091
              containerPort: {{.Values.kafka.observaikafka.targetPort}}
              protocol: TCP
            - name: http-9092
              containerPort: {{.Values.kafka.observaikafka.targetPort1}}
              protocol: TCP
            - name: http-9093
              containerPort: {{.Values.kafka.observaikafka.targetPort2}}
              protocol: TCP
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: KAFKA_ZOOKEEPER_CONNECT
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: KAFKA_ADVERTISED_LISTENERS
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP   
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: KAFKA_INTER_BROKER_LISTENER_NAME            
          imagePullPolicy: IfNotPresent
      restartPolicy: Always



