apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: '3.3'
    storage:
      size: {{.Values.kafka.storage.size}}
      type: {{.Values.kafka.storage.type}}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9093
        type: route
        tls: true
    version: {{.Values.kafka.version}}
    replicas: {{.Values.kafka.replicas}}
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      size: {{.Values.zookeeper.storage.size}}
      type: {{.Values.zookeeper.storage.type}}
    replicas: {{.Values.zookeeper.replicas}}