apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-config
  namespace: {{.Values.Namespace}}
data:
  APP_PORT: "{{.Values.querybackend.config.APP_PORT}}"
  APP_HOST: "{{.Values.querybackend.config.APP_HOST}}"
  MONGODB_URL: "{{.Values.querybackend.config.MONGODB_URL}}"