apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.Namespace}}
spec:
  type: {{ .Values.querybackend.service.type }}
  ports:
    - port: {{ .Values.querybackend.service.ports.port }}
      targetPort: {{.Values.querybackend.service.ports.targetPort}}
      protocol: TCP
      name: http
  selector:
    app: {{.Values.name}}
