apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: observai-persistance-api 
  namespace: observai-pipeline
  labels:
      app.kubernetes.io/part-of: observai
      app.openshift.io/runtime: quarkus
spec:
  strategy:
    type: Rolling
    rollingParams:
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  triggers:
    - type: ConfigChange
  replicas: 1
  selector:
      app: observai-persistance-api 
      deploymentconfig: observai-persistance-api
  template:
    metadata:
      labels:
        app: observai-persistance-api
        deploymentconfig: observai-persistance-api
    spec:
      imagePullSecrets:
        - name: sharanya-pull-secret
      containers:
        - name: test-observai-persistance-api
          image: >-
            quay.io/zagaos/test-observai-persistance-api
          env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: APP_PORT
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: APP_HOST
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: MONGODB_URL
            - name: TRACE_BOOTSTRAP_URL
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: TRACE_BOOTSTRAP_URL
            - name: TRACE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: TRACE_TOPIC
            - name: TRACE_OFFSET_RESET
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: TRACE_OFFSET_RESET
            - name: LOG_BOOTSTRAP_URL
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: LOG_BOOTSTRAP_URL
            - name: LOG_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: LOG_TOPIC
            - name: LOG_OFFSET_RESET
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: LOG_OFFSET_RESET                          
            - name: METRIC_BOOTSTRAP_URL
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: METRIC_BOOTSTRAP_URL
            - name: METRIC_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: METRIC_TOPIC
            - name: METRIC_OFFSET_RESET
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: METRIC_OFFSET_RESET  
            - name: KEPLER_BOOTSTRAP_URL
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: KEPLER_BOOTSTRAP_URL
            - name: KEPLER_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: KEPLER_TOPIC 
            - name: KEPLER_OFFSET_RESET
              valueFrom:
                configMapKeyRef:
                  name: test-observai-backend-config
                  key: KEPLER_OFFSET_RESET                                 
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: {}




