apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
 name: {{.Values.name}}
 namespace: testing-workspace
spec:
 {{- if .Values.enableLogicalBackup.enabled }}
 enableLogicalBackup: true
 {{- end }}
 allowedSourceRanges: null
 teamId: {{ .Values.labels.team }}
 tolerations:
   - key: dedicated
     operator: Equal
     value: postgresql
     effect: NoSchedule
 {{- with .Values.users }}
 users:
   {{- toYaml . | nindent 4 }}
 {{- end }}
 {{- with .Values.databases }}
 databases:
   {{- toYaml . | nindent 4 }}
 {{- end }}
 {{- if .Values.enablePreparedDatabases.enabled }}
 preparedDatabases: {{- toYaml .Values.preparedDatabases | nindent 4 }}
 {{- end }}
 {{- if .Values.enableInitContainers.enabled }}
 initContainers: {{- toYaml .Values.initContainers | nindent 2 }}
 {{- end }}
 numberOfInstances: {{ .Values.numberOfInstances }}
 postgresql:
   version: {{ .Values.postgresql.version | quote }}
   {{- with .Values.parameters }}
   parameters: {{- toYaml . | nindent 6 }}
   {{- end }}
 resources:
   limits:
     cpu: {{ .Values.limits.cpu }}
     memory: {{ .Values.limits.memory }}
   requests:
     cpu: {{ .Values.requests.cpu }}
     memory: {{ .Values.requests.memory }}
 volume:
   size: {{ .Values.size }}
#    storageClass: {{ .Values.storageClass }}
#  {{- if .Values.enableAdditionalVolumes.enabled }}
#  additionalVolumes: {{- toYaml .Values.additionalVolumes | nindent 2 }}
#  {{- end }}