apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata: 
  name: observai-ui
  namespace: testing-workspace
spec:
  params:
  - name: url
  workspaces:
    - name: shared-workspace
  tasks:
#git clone task
    - name: clone-from-git
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params: 
        - name: url
          value: $(params.url)
#Oc Tasks
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
      - name: SCRIPT
        value: | 
                oc apply -f ./oc_manifests/buildConfig.yaml
                oc apply -f ./oc_manifests/deploymentConfig.yaml                
      workspaces:
      - name: manifest-dir
        workspace: shared-workspace