apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata: 
  name: observai-ui-pipeline
  namespace: observai-pipeline
spec:
  params:
  - name: url
  - name: revision
  workspaces:
    - name: shared-workspace
  tasks:
#git clone task
    - name: clone-from-git
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params: 
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
#Oc Tasks
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
      - name: SCRIPT
        value: | 
                oc apply -f tekton/frontend/oc_manifests/buildConfig.yaml
                oc apply -f tekton/frontend/oc_manifests/deploymentConfig.yaml     
                oc apply -f tekton/frontend/oc_manifests/service.yaml
                oc apply -f tekton/frontend/oc_manifests/route.yaml
      workspaces:
      - name: manifest-dir
        workspace: shared-workspace
      runAfter:
      - clone-from-git