apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-binding-ui
  namespace: observai-main
spec:
  params:
    - name: url
      value: $(body.repository.clone_url)




