kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-volume-claim-2
  namespace: testing-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: shared-volume-2
  storageClassName: lvms-vg1
  volumeMode: Filesystem

