apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: testing-autoinst
  namespace: testing-workspace
spec:
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "10.96.142.154:4317"
      - name: OTEL_LOGS_EXPORTER
        value: otlp

