apiVersion: v1
kind: Secret
metadata:
  name: zaga-observez-dev-userpass
  namespace: testing-workspace
type: Opaque
stringData:
  password: Observabilitydb@2023

--- 

apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: zaga-observez-dev-user
  namespace: testing-workspace
spec:
  passwordSecretKeyRef:
    name: zaga-observez-dev-userpass
    # Match to metadata.name of the User Secret
    key: password
  username: observability-dev-user
  db: telemetry-data
  # authentication database
  mongodbResourceRef:
    name: zaga-observez-dev
    # Match to MongoDB resource using authenticaiton
    # need orgId and projectName in config map of mongodb resource
  roles:
    - db: telemetry-data
      name: readWrite