apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.orderproject.name }}
  namespace: {{.Values.Namespace}}
  annotations:
    instrumentation.opentelemetry.io/inject-java: "true"
  labels:
    app: {{ .Values.orderproject.name }}
    app.openshift.io/runtime: {{ .Values.orderproject.icon }}
    app.kubernetes.io/part-of: instrumented-apps
spec:
  replicas: {{ .Values.orderproject.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.orderproject.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.orderproject.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.orderproject.image.repository }}:{{ .Values.orderproject.image.tag}}"
          ports:
            - name: http
              containerPort: {{ .Values.orderproject.service.ports.port }}
              protocol: TCP
          env:
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: order-project-config
                  key: POSTGRES_URL
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: order-project-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: order-project-config
                  key: POSTGRES_PASSWORD

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    instrumentation.opentelemetry.io/inject-java: "true"
  name: {{ .Values.vendorproject.name }}
  namespace: {{.Values.Namespace}}
  labels:
    app: {{ .Values.vendorproject.name }}
    app.openshift.io/runtime: {{ .Values.vendorproject.icon }}
    app.kubernetes.io/part-of: instrumented-apps
spec:
  replicas: {{ .Values.vendorproject.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.vendorproject.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.vendorproject.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.vendorproject.image.repository }}:{{ .Values.vendorproject.image.tag}}"
          ports:
            - name: http
              containerPort: {{ .Values.vendorproject.service.ports.port }}
              protocol: TCP
          env:
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: vendor-project-config
                  key: POSTGRES_URL
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: vendor-project-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: vendor-project-config
                  key: POSTGRES_PASSWORD
            - name: APP_APIURL
              valueFrom:
                configMapKeyRef:
                  name: vendor-project-config
                  key: APP_APIURL