apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-route
spec:
  selector:
    app: {{ .Release.Name }}-frontend
  to:
    kind: Service
    name: {{ .Release.Name }}-service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: 8080
