orderproject:
  name: order-project
  icon: spring-boot
  replicaCount: 1
  image:
    repository: mugicoder13/order-project
    tag: latest
  service:
    type: ClusterIP
    ports:
      port: 5089
      targetPort: 5089

vendorproject:
  name: vendor-project
  icon: spring-boot
  replicaCount: 1
  image:
    repository: mugicoder13/vendor-project
    tag: latest
  service:
    type: ClusterIP
    ports:
      port: 8080
      targetPort: 8080

