frontend:
  replicaCount: 1
  image:
    repository: sharon0706/observai_zaga_ui
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

backend:
  replicaCount: 1
  image:
    repository: sharon0706/observai_backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080