apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{.Values.Namespace}}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.ports.port }}
      targetPort: {{.Values.backend.service.ports.targetPort}}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-backend

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-query-backend
  namespace: {{.Values.Namespace}}
spec:
  type: {{ .Values.querybackend.service.type }}
  ports:
    - port: {{ .Values.querybackend.service.ports.port }}
      targetPort: {{.Values.querybackend.service.ports.targetPort}}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-query-backend

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{.Values.Namespace}}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.ports.port }}
      targetPort: {{.Values.frontend.service.ports.targetPort}}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-ui

---



