apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-commit-listener
  namespace: observai-pipeline
spec:
  triggers:
    - name: github-trigger
      bindings:
      - ref: github-binding
      template:
        ref: github-template