kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-github-commit-listener
  namespace: observai-pipeline
spec:
  to:
    kind: Service
    name: el-github-commit-listener
  tls:
    termination: edge

