apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}
  labels:
    app: {{.Release.Name}}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
        
    exporters:
      logging:
        loglevel: info


    service:
      pipelines:
        metrics:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - logging

        traces:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - logging

        logs:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - logging

