apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.adminCredentials}}
type: Opaque
stringData:
  Username: {{.Values.admin.username}}
  Password: {{.Values.admin.password}}
  FirstName: {{.Values.admin.firstname}}
  LastName: {{.Values.admin.lastname}}